Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
ClassVars:
  Enabled: false
Metrics/BlockLength:
  Max: 200
Metrics/LineLength:
  Max: 140
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
